In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
y = data.iloc[:,13]
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [4]:
data.shape

(10000, 14)

In [5]:
X = data.iloc[:,3:13]
y = data.iloc[:,13]

In [6]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [7]:
geo = pd.get_dummies(X['Geography'], drop_first=True)
gender = pd.get_dummies(X["Gender"], drop_first=True)

In [8]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [9]:
X.drop(['Gender', 'Geography'], inplace = True, axis = 1)
X = pd.concat([X, geo, gender], axis =1)
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0                  1        101348.88        0      0     0  
1                  1        112542.58        0      1     0  
2                  0        113931.57        0      0     0  
3                  0         93826.63        0      0     0  
4                  1         79084.10        0      1     0  
...              ...              ...      ...    ...   ...  
9995               0         96270.64        0      0     1  
9996               1        101699.77        0      0     1  
9997               1         42085.58        0      0     0  
9998               0         92888.52        1      0     1  
9999               0         38190.78        0      0     0  

[10000 rows x 11 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [12]:
X_train = sc.fit_transform(X_train)
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [13]:
X_test = sc.fit_transform(X_test)

In [14]:
!pip install keras

In [15]:
!pip install tensorflow

In [16]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import PReLU,LeakyReLU,ELU
from keras.layers import Dropout

In [18]:
classifier = Sequential()
classifier.add(Dense(units=6, kernel_initializer="he_uniform", activation = 'relu', input_dim = 11))
classifier.add(Dense(units=6, kernel_initializer='he_uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer='glorot_uniform', activation = 'sigmoid'))
classifier.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
model_history = classifier.fit(X_train, y_train, validation_split=0.33, batch_size= 10, epochs =100)

Epoch 1/100
536/536 [==============================] - 1s 1ms/step - loss: 0.5301 - accuracy: 0.7626 - val_loss: 0.4863 - val_accuracy: 0.7952
Epoch 2/100
536/536 [==============================] - 1s 987us/step - loss: 0.4705 - accuracy: 0.7970 - val_loss: 0.4621 - val_accuracy: 0.7959
Epoch 3/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4510 - accuracy: 0.7974 - val_loss: 0.4487 - val_accuracy: 0.7955
Epoch 4/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4388 - accuracy: 0.7990 - val_loss: 0.4385 - val_accuracy: 0.8005
Epoch 5/100
536/536 [==============================] - 1s 993us/step - loss: 0.4292 - accuracy: 0.8065 - val_loss: 0.4308 - val_accuracy: 0.8084
Epoch 6/100
536/536 [==============================] - 1s 1ms/step - loss: 0.4209 - accuracy: 0.8162 - val_loss: 0.4241 - val_accuracy: 0.8186
Epoch 7/100
536/536 [==============================] - 1s 998us/step - loss: 0.4134 - accuracy: 0.8224 - val_loss: 0.4178 - val_accuracy: 

536/536 [==============================] - 1s 988us/step - loss: 0.3279 - accuracy: 0.8645 - val_loss: 0.3627 - val_accuracy: 0.8550
Epoch 58/100
536/536 [==============================] - 1s 1ms/step - loss: 0.3277 - accuracy: 0.8642 - val_loss: 0.3631 - val_accuracy: 0.8542
Epoch 59/100
536/536 [==============================] - 1s 994us/step - loss: 0.3280 - accuracy: 0.8658 - val_loss: 0.3630 - val_accuracy: 0.8501
Epoch 60/100
536/536 [==============================] - 1s 997us/step - loss: 0.3278 - accuracy: 0.8645 - val_loss: 0.3624 - val_accuracy: 0.8493
Epoch 61/100
536/536 [==============================] - 1s 978us/step - loss: 0.3278 - accuracy: 0.8649 - val_loss: 0.3624 - val_accuracy: 0.8516
Epoch 62/100
536/536 [==============================] - 1s 1ms/step - loss: 0.3280 - accuracy: 0.8649 - val_loss: 0.3620 - val_accuracy: 0.8512
Epoch 63/100
536/536 [==============================] - 1s 977us/step - loss: 0.3277 - accuracy: 0.8670 - val_loss: 0.3611 - val_accuracy: 0.

In [22]:
y_pred = classifier.predict(X_test)
y_pred
y_pred = (y_pred>0.5)
y_pred

63/63 [==============================] - 0s 544us/step


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [23]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)
score

0.862

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1532,   63],
       [ 213,  192]], dtype=int64)